# code: utf-8
# author: xavierniu
# a tool for downloading files from Baidu Netdisk by Aria2

import re
import subprocess
import os

HOME = os.path.expanduser('~')

# Baidu Netdisk direct link extract by 百度网盘万能助手, for more information please visit https://www.baiduyun.wiki/zh-cn/assistant.html
DOWNLOAD_LINKS_FROM_BAIDU = """
黑暗之源0.2攻略.docx：http://pcs.baidu.com/rest/2.0/pcs/file?method=download&path=%2F%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9_20191020_183139%2F%E9%BB%91%E6%9A%97%E4%B9%8B%E6%BA%900.2%E6%94%BB%E7%95%A5.docx&app_id=624966
Vagrant Rape0.2z赞助群内测.rar：http://pcs.baidu.com/rest/2.0/pcs/file?method=download&path=%2F%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9_20191020_183139%2FVagrant%20Rape0.2z%E8%B5%9E%E5%8A%A9%E7%BE%A4%E5%86%85%E6%B5%8B.rar&app_id=624966
黑暗之源ver0.3-PC.rar：http://pcs.baidu.com/rest/2.0/pcs/file?method=download&path=%2F%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9_20191020_183139%2F%E9%BB%91%E6%9A%97%E4%B9%8B%E6%BA%90ver0.3-PC.rar&app_id=624966
jy021pc-0.21-pc.zip：http://pcs.baidu.com/rest/2.0/pcs/file?method=download&path=%2F%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%
"""

# Cookie which you could get it by EditThisCookie, a chrome extention for editing and viewing cookie. 
# Before export cookies, the output format shoule be changed from default to "Semicolon separated name=value paris".
COOKIE = """
// Semicolon separated Cookie File
// This file was generated by EditThisCookie
// Details: http://www.ietf.org/rfc/rfc2109.txt
// Example: http://www.tutorialspoint.com/javascript/javascript_cookies.htm
BAIDUID=CA5957817B5AF02681BD0CD41D3629ED:FG=1;BDORZ=FFFB88E999055A3F8A630C64834BD6D0;BDUSS=J0bndMSEhNdUlYalJtZ05NTTlITG1NMlFINHBnS29SU3RudHU2aDUzMEF1dE5kRUFBQUFBJCQAAAAAAAAAAAEAAAAF7UWheWdvd2NlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtrF0ALaxdaj;BIDUPSID=CA5957817B5AF02681BD0CD41D3629ED;cflag=13%3A3;PSTM=1571537294;PANPSC=6824420581147142638%3ADJI9ZdfpjgIwjQDC2v7%2B0aPTzGELv%2B1d4fBC1r%2FapuQr2wqYbSNJzPBl8XefSTKb365hCYkedGDhtZAXVT9Tf9thklJhx6JJe9%2BcaRmZd%2FdFah9uWgECZ7LhpZN4hDe4DZqVXlRqcuai%2BY1X7udr9G2gud9gLjYtRogbeq4A%2FVImU589kUerfvf%2F25ehPR0XfPVXoOSO8Qs7qAHgpfUwRg%3D%3D;PANWEB=1;SCRC=d4744a92161df5a692bf6bed47ffd411;STOKEN=908cb8e566f85588f77946d563e19e37bae1c3c370234cd4a14471a437bf3ef1;pan_login_way=1;
"""
# save to
DOWNLOAD_DIR = "%s/Downloads" % HOME
# aria2 conf
ARIA2_CONF_PATH = "%s/.aria2/aria2.conf" % HOME

# User agent allows to fake downloading requests as what a real browser does. DO NOT edit it if you have no idea what it is.
USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
# Download links for batch downloading with aria2. DO NOT edit it if you have no idea what it is.
DOWNLOAD_LINK_FILE = "%s/Downloads/baidu.aria2" % HOME

download_link_file = open(DOWNLOAD_LINK_FILE, "w")
download_link_str = DOWNLOAD_LINKS_FROM_BAIDU.split("\n")
download_link_str = download_link_str[1:-1]

for link_str in download_link_str:
    link = re.search(r'(http:\/\/pcs\.baidu\.com.*)$', link_str).group(0)
    name = re.search(r'.*(?=：http:\/\/pcs\.baidu\.com)', link_str).group(0)
    download_link_file.write("%s\n" % link)
    download_link_file.write("  dir=%s\n" % DOWNLOAD_DIR)
    download_link_file.write("  out=%s\n" % name)

download_link_file.close()

cookie = COOKIE.split("\n")[-2].split(";")[:-1]
COOKIE = "; ".join(cookie)

subprocess.call("aria2c --conf-path='%s' --header 'Cookie: %s' --header 'User-Agent: %s' -i '%s'" % (ARIA2_CONF_PATH, COOKIE, USER_AGENT, DOWNLOAD_LINK_FILE), shell=True)
